name: Build Dist
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.4.0
      - env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |-
          npm install
          npm run docs:build
          git config --global user.email "github-actions@gmail.com"
          git config --global user.name "github-actions"
          git add --all
          git commit -m "update by github actions"
          git pull origin master
          git push origin master
