name: Build Dist
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.4.0
      - run: npm install
      - run: npm run docs:build
      - run: git config --global user.email "github-actions@gmail.com"
      - run: git config --global user.name "github-actions"
      - run: git add --all
      - run: git commit -m "update by github actions"
      - run: git push origin master
